services:
  postgres:
    image: postgres:16-alpine
    container_name: clms_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: clms
      POSTGRES_PASSWORD: clms
      POSTGRES_DB: clms
    ports:
      - "5432:5432"
    volumes:
      - clms_pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: clms_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:latest
    container_name: clms_minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: clms
      MINIO_ROOT_PASSWORD: clms12345
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - clms_minio_data:/data

volumes:
  clms_pg_data:
  clms_minio_data:
