// ─────────────────────────────────────────────────────────────────
// CLMS — NABL Calibration Procedure Library: MECHANICAL (Dimensional)
// ─────────────────────────────────────────────────────────────────
// References: EURAMET cg-2 (calipers), cg-15 (micrometers), DKD-R 6-1 family,
// NABL 122-02, IS 3651 / IS 2967 etc. Type-B values are µm-level engineering
// defaults; accredited values are editable in the UI.

import { Procedure, pts, tb, range, hysteresisExtra, R3 } from './types';

const MM_ALT = ['inch', 'µm'];
const ANGLE_ALT = ['rad', 'arcmin'];

export const MECHANICAL: Procedure[] = [
  // ── Dimension — Length (linear measuring instruments) ───────────────
  {
    id: 'mech-vernier-digital-caliper',
    label: 'Vernier / Digital Caliper',
    discipline: 'Mechanical',
    subDiscipline: 'Dimension — Length',
    unit: 'mm',
    points: pts('mm', [0, 25, 50, 100, 150, 200]),
    typeB: tb('mm', 0.0005, 0.01, [hysteresisExtra('mm', 0.005)]),
    units: MM_ALT.concat('mm'),
    ranges: [
      range('External measurement', 'mm', [0, 25, 50, 100, 150, 200], tb('mm', 0.0005, 0.01, [hysteresisExtra('mm', 0.005)]), { altUnits: MM_ALT, rangeText: '0 – 300 mm' }),
      range('Internal measurement', 'mm', [10, 25, 50, 100], tb('mm', 0.0005, 0.01), { altUnits: MM_ALT }),
      range('Depth measurement', 'mm', [25, 50, 100], tb('mm', 0.0005, 0.01), { altUnits: MM_ALT }),
    ],
    procedureText:
      'The caliper is calibrated for external, internal and depth measurement using grade-1 gauge blocks (and a gauge-block holder for internal jaws) at selected points across the range. At each point the indicated value is compared with the true gauge-block length, the error and inter-jaw parallelism being recorded after temperature stabilisation at 20 °C. Measurements follow EURAMET cg-2 with the resolution and repeatability treated as Type-B contributors.',
    nablReference: 'EURAMET cg-2',
    referenceStandard: 'Grade-1 slip gauge set / gauge block holder',
  },
  {
    id: 'mech-outside-micrometer',
    label: 'Outside Micrometer',
    discipline: 'Mechanical',
    subDiscipline: 'Dimension — Length',
    unit: 'mm',
    points: pts('mm', [0, 5.12, 10.24, 15.36, 20.48, 25]),
    typeB: tb('mm', 0.0003, 0.001, [hysteresisExtra('mm', 0.001)]),
    units: MM_ALT.concat('mm'),
    ranges: [
      range('External length (0–25 mm)', 'mm', [0, 5.12, 10.24, 15.36, 20.48, 25], tb('mm', 0.0003, 0.001, [hysteresisExtra('mm', 0.001)]), { altUnits: MM_ALT, rangeText: '0 – 25 mm' }),
    ],
    procedureText:
      'The outside micrometer is calibrated against grade-1 gauge blocks selected to exercise the full revolution of the thimble (e.g. 5.12, 10.24, 15.36, 20.48 mm). Anvil/spindle flatness and parallelism are checked with optical flats, and measuring force is verified. Errors are recorded with a constant ratchet/friction-drive force after stabilisation at 20 °C per EURAMET cg-15.',
    nablReference: 'EURAMET cg-15',
    referenceStandard: 'Grade-1 slip gauge set, optical flat',
  },
  {
    id: 'mech-inside-micrometer',
    label: 'Inside Micrometer',
    discipline: 'Mechanical',
    subDiscipline: 'Dimension — Length',
    unit: 'mm',
    points: pts('mm', [25, 50, 75, 100, 150]),
    typeB: tb('mm', 0.0008, 0.001, [hysteresisExtra('mm', 0.002)]),
    units: MM_ALT.concat('mm'),
    procedureText:
      'The inside micrometer (with its extension rods) is calibrated using gauge blocks held between accessory jaws, calibrated setting rings, or a horizontal length comparator at selected internal dimensions. Each rod combination is verified for length error and the spindle for parallelism. The method follows EURAMET cg-15 with rod-fit and resolution included as Type-B contributors.',
    nablReference: 'EURAMET cg-15',
    referenceStandard: 'Setting rings / grade-1 slip gauges',
  },
  {
    id: 'mech-depth-micrometer',
    label: 'Depth Micrometer',
    discipline: 'Mechanical',
    subDiscipline: 'Dimension — Length',
    unit: 'mm',
    points: pts('mm', [0, 6.25, 12.5, 18.75, 25]),
    typeB: tb('mm', 0.0005, 0.001, [hysteresisExtra('mm', 0.002)]),
    units: MM_ALT.concat('mm'),
    procedureText:
      'The depth micrometer is calibrated on a surface plate using gauge blocks wrung to a reference and the base rested on a parallel, comparing the indicated depth with the gauge-block stack at points across each rod. Base flatness and squareness of the spindle to the base are checked. Resolution and repeatability are treated as Type-B per EURAMET cg-15.',
    nablReference: 'EURAMET cg-15',
    referenceStandard: 'Grade-1 slip gauges on surface plate',
  },
  {
    id: 'mech-bench-micrometer',
    label: 'Bench Micrometer',
    discipline: 'Mechanical',
    subDiscipline: 'Dimension — Length',
    unit: 'mm',
    points: pts('mm', [0, 10, 25, 50, 75, 100]),
    typeB: tb('mm', 0.0002, 0.001, [hysteresisExtra('mm', 0.0005)]),
    units: MM_ALT.concat('mm'),
    procedureText:
      'The bench (floating-anvil) micrometer is calibrated as a comparator using grade-0/1 gauge blocks at points across the range under controlled constant measuring force. Linearity, repeatability and measuring-force consistency are evaluated. Calibration is performed at 20 °C following EURAMET cg-15.',
    nablReference: 'EURAMET cg-15',
    referenceStandard: 'Grade-0 slip gauge set',
  },
  {
    id: 'mech-vernier-height-gauge',
    label: 'Vernier Height Gauge',
    discipline: 'Mechanical',
    subDiscipline: 'Dimension — Length',
    unit: 'mm',
    points: pts('mm', [0, 50, 100, 150, 200, 300]),
    typeB: tb('mm', 0.0006, 0.01, [hysteresisExtra('mm', 0.005)]),
    units: MM_ALT.concat('mm'),
    procedureText:
      'The height gauge is calibrated on a grade-0 surface plate by comparing scriber/probe height against wrung gauge-block stacks (or a calibrated step master) at points across the range. Beam straightness, scriber squareness and base seating are verified. Errors are recorded after stabilisation at 20 °C per EURAMET cg-2 principles.',
    nablReference: 'EURAMET cg-2',
    referenceStandard: 'Grade-1 slip gauges on grade-0 surface plate',
  },
  {
    id: 'mech-vernier-depth-gauge',
    label: 'Vernier Depth Gauge',
    discipline: 'Mechanical',
    subDiscipline: 'Dimension — Length',
    unit: 'mm',
    points: pts('mm', [0, 25, 50, 100, 150, 200]),
    typeB: tb('mm', 0.0006, 0.01, [hysteresisExtra('mm', 0.005)]),
    units: MM_ALT.concat('mm'),
    procedureText:
      'The vernier depth gauge is calibrated on a surface plate using gauge-block stacks, comparing the indicated depth against the true stack height with the base resting on parallels. Base flatness and blade squareness are checked. Resolution and repeatability are included as Type-B contributors per EURAMET cg-2.',
    nablReference: 'EURAMET cg-2',
    referenceStandard: 'Grade-1 slip gauges on surface plate',
  },
  {
    id: 'mech-steel-rule-scale',
    label: 'Steel Rule / Scale',
    discipline: 'Mechanical',
    subDiscipline: 'Dimension — Length',
    unit: 'mm',
    points: pts('mm', [0, 100, 200, 300, 500, 1000]),
    typeB: tb('mm', 0.01, 0.5, [hysteresisExtra('mm', 0.1)]),
    units: MM_ALT.concat('mm'),
    procedureText:
      'The steel rule is calibrated against a calibrated reference glass scale or steel scale read under a measuring microscope/profile projector at decade intervals over the full length. Graduation interval errors and accumulated length error are recorded at 20 °C. Reading resolution and parallax are treated as Type-B per IS 1481.',
    nablReference: 'IS 1481',
    referenceStandard: 'Calibrated reference glass / line scale',
  },
  {
    id: 'mech-measuring-tape',
    label: 'Measuring Tape',
    discipline: 'Mechanical',
    subDiscipline: 'Dimension — Length',
    unit: 'mm',
    points: pts('mm', [0, 1000, 2000, 5000, 10000, 30000]),
    typeB: tb('mm', 0.05, 1, [hysteresisExtra('mm', 0.5)]),
    units: ['m', 'inch', 'mm'],
    procedureText:
      'The measuring tape is calibrated against a calibrated bench tape comparator or reference steel tape on a flat bed under a standard tension and at 20 °C, comparing graduations at intervals over the full length. Tape error, tension and thermal corrections are evaluated; reading resolution is a Type-B contributor.',
    nablReference: 'OIML R35 / IS 1269',
    referenceStandard: 'Reference standard tape / tape comparator bench',
  },
  {
    id: 'mech-glass-scale',
    label: 'Glass Scale',
    discipline: 'Mechanical',
    subDiscipline: 'Dimension — Length',
    unit: 'mm',
    points: pts('mm', [0, 25, 50, 100, 150, 200]),
    typeB: tb('mm', 0.0005, 0.001, [hysteresisExtra('mm', 0.0005)]),
    units: MM_ALT.concat('mm'),
    procedureText:
      'The glass line scale is calibrated against a reference line scale on a calibrated line-measuring machine / measuring microscope, comparing graduation line positions at decade intervals. Pitch and accumulated length errors are evaluated at 20 °C with thermal-expansion and optical-alignment corrections applied. Microscope reading resolution is a Type-B contributor.',
    nablReference: 'NABL 122-02',
    referenceStandard: 'Reference line scale / line-measuring machine',
  },

  // ── Dimension — Displacement (dial / probe gauges) ──────────────────
  {
    id: 'mech-dial-indicator-plunger',
    label: 'Dial Indicator / Plunger Gauge',
    discipline: 'Mechanical',
    subDiscipline: 'Dimension — Displacement',
    unit: 'mm',
    points: pts('mm', [0, 0.2, 0.5, 1, 2, 5, 10]),
    typeB: tb('mm', 0.0005, 0.001, [hysteresisExtra('mm', 0.002)]),
    units: MM_ALT.concat('mm'),
    procedureText:
      'The dial / plunger indicator is calibrated on a calibrated indicator-checking instrument (or against gauge blocks in a setting fixture) over the full plunger travel in both increasing and decreasing directions. Errors, hysteresis, repeatability and measuring force are determined per IS 2092 / EURAMET principles. Hysteresis and resolution are Type-B contributors.',
    nablReference: 'IS 2092',
    referenceStandard: 'Indicator calibration tester / grade-1 slip gauges',
  },
  {
    id: 'mech-dial-test-indicator-lever',
    label: 'Dial Test Indicator (Lever)',
    discipline: 'Mechanical',
    subDiscipline: 'Dimension — Displacement',
    unit: 'mm',
    points: pts('mm', [0, 0.1, 0.2, 0.4, 0.6, 0.8]),
    typeB: tb('mm', 0.0004, 0.001, [hysteresisExtra('mm', 0.002)]),
    units: MM_ALT.concat('mm'),
    procedureText:
      'The lever-type (test) indicator is calibrated on an indicator-checking instrument with the stylus set at the correct contact angle, traversing the full ball-tip travel in both directions. Cosine-error from stylus angle, hysteresis and repeatability are evaluated per IS 11498. Resolution and hysteresis are treated as Type-B.',
    nablReference: 'IS 11498',
    referenceStandard: 'Indicator calibration tester',
  },
  {
    id: 'mech-dial-bore-gauge',
    label: 'Dial Bore Gauge',
    discipline: 'Mechanical',
    subDiscipline: 'Dimension — Displacement',
    unit: 'mm',
    points: pts('mm', [0, 0.05, 0.1, 0.15, 0.2]),
    typeB: tb('mm', 0.0008, 0.001, [hysteresisExtra('mm', 0.002)]),
    units: MM_ALT.concat('mm'),
    procedureText:
      'The dial bore gauge is calibrated for its built-in indicator travel using gauge blocks or a setting ring, and the displayed deviation is compared with calibrated setting rings / gauge-block fixtures at the bore nominal. Indicator linearity, hysteresis and centralising-shoe effects are evaluated. Resolution and repeatability are Type-B contributors.',
    nablReference: 'NABL 122-02',
    referenceStandard: 'Setting rings / grade-1 slip gauge fixture',
  },
  {
    id: 'mech-dial-thickness-gauge',
    label: 'Dial Thickness Gauge',
    discipline: 'Mechanical',
    subDiscipline: 'Dimension — Displacement',
    unit: 'mm',
    points: pts('mm', [0, 1, 2, 5, 10]),
    typeB: tb('mm', 0.0005, 0.001, [hysteresisExtra('mm', 0.002)]),
    units: MM_ALT.concat('mm'),
    procedureText:
      'The dial thickness gauge is calibrated by inserting grade-1 gauge blocks between the anvil and contact at points across the range in both directions, comparing the indicated thickness with the gauge-block length under the specified contact force. Anvil flatness, hysteresis and repeatability are evaluated. Resolution is a Type-B contributor.',
    nablReference: 'NABL 122-02',
    referenceStandard: 'Grade-1 slip gauge set',
  },

  // ── Dimension — Gauges (limit / form gauges) ────────────────────────
  {
    id: 'mech-slip-gauge-block-set',
    label: 'Slip Gauge / Gauge Block Set',
    discipline: 'Mechanical',
    subDiscipline: 'Dimension — Gauges',
    unit: 'mm',
    points: pts('mm', [1.005, 1.5, 5, 10, 25, 50, 100]),
    typeB: tb('mm', 0.00005, 0.0001, [hysteresisExtra('mm', 0.00005)]),
    units: MM_ALT.concat('mm'),
    procedureText:
      'Each gauge block is calibrated by mechanical or interferometric comparison against reference blocks of higher grade on a gauge-block comparator at 20 °C, measuring central length and evaluating length deviation, flatness and parallelism (variation in length). Wringing, thermal and comparator effects are included as Type-B contributors per ISO 3650.',
    nablReference: 'ISO 3650',
    referenceStandard: 'Reference grade-K/00 gauge block set, comparator',
  },
  {
    id: 'mech-plain-plug-gauge',
    label: 'Plain Plug Gauge',
    discipline: 'Mechanical',
    subDiscipline: 'Dimension — Gauges',
    unit: 'mm',
    points: pts('mm', [3, 6, 10, 20, 50]),
    typeB: tb('mm', 0.0003, 0.001, [hysteresisExtra('mm', 0.0005)]),
    units: MM_ALT.concat('mm'),
    procedureText:
      'The plain plug (GO/NO-GO) gauge is calibrated on a horizontal/floating-carriage length comparator against gauge blocks, measuring the gauge diameter at several positions and orientations to assess size, roundness and taper. Wear allowance and tolerance class (IS 3485 / ISO 1938) are verified. Comparator and resolution effects are Type-B.',
    nablReference: 'IS 3485',
    referenceStandard: 'Grade-1 slip gauges / length comparator',
  },
  {
    id: 'mech-plain-ring-gauge',
    label: 'Plain Ring Gauge',
    discipline: 'Mechanical',
    subDiscipline: 'Dimension — Gauges',
    unit: 'mm',
    points: pts('mm', [5, 10, 20, 50, 100]),
    typeB: tb('mm', 0.0004, 0.001, [hysteresisExtra('mm', 0.0005)]),
    units: MM_ALT.concat('mm'),
    procedureText:
      'The plain ring gauge is calibrated on a horizontal length comparator or universal measuring machine using a two-point internal measurement against gauge blocks and reference setting masters, measured in two/three diametral planes to assess size, roundness and taper. Tolerance class is verified per IS 3485 / ISO 1938. Probe-fit and resolution are Type-B contributors.',
    nablReference: 'IS 3485',
    referenceStandard: 'Setting rings / grade-1 slip gauges, length comparator',
  },
  {
    id: 'mech-snap-gauge',
    label: 'Snap Gauge',
    discipline: 'Mechanical',
    subDiscipline: 'Dimension — Gauges',
    unit: 'mm',
    points: pts('mm', [5, 10, 25, 50, 100]),
    typeB: tb('mm', 0.0004, 0.001, [hysteresisExtra('mm', 0.001)]),
    units: MM_ALT.concat('mm'),
    procedureText:
      'The snap (gap) gauge GO and NO-GO anvils are calibrated by inserting grade-1 gauge blocks between the anvils on a length comparator/fixture, measuring the effective gap at several positions to assess size and parallelism. Tolerance class is verified per IS 3477. Resolution and anvil parallelism are Type-B contributors.',
    nablReference: 'IS 3477',
    referenceStandard: 'Grade-1 slip gauge set',
  },
  {
    id: 'mech-thread-plug-ring-gauge',
    label: 'Thread Plug / Ring Gauge',
    discipline: 'Mechanical',
    subDiscipline: 'Dimension — Gauges',
    unit: 'mm',
    points: pts('mm', [3, 6, 10, 20, 30]),
    typeB: tb('mm', 0.0008, 0.001, [hysteresisExtra('mm', 0.001)]),
    units: MM_ALT.concat('mm'),
    procedureText:
      'The thread plug/ring gauge is calibrated for major, minor and effective (pitch) diameter, pitch and flank angle using the three-wire method (plug) or thread-measuring cylinders (ring) on a floating-carriage micrometer / measuring machine. Element errors are evaluated against the thread standard (IS 3641 / ISO 1502). Wire-fit, pitch and resolution are Type-B contributors.',
    nablReference: 'IS 3641',
    referenceStandard: 'Calibrated thread-measuring wires / floating carriage micrometer',
  },
  {
    id: 'mech-feeler-gauge',
    label: 'Feeler Gauge',
    discipline: 'Mechanical',
    subDiscipline: 'Dimension — Gauges',
    unit: 'mm',
    points: pts('mm', [0.05, 0.1, 0.2, 0.5, 1]),
    typeB: tb('mm', 0.0003, 0.001, [hysteresisExtra('mm', 0.0005)]),
    units: MM_ALT.concat('mm'),
    procedureText:
      'Each feeler-gauge blade thickness is measured at several points along its length with a calibrated bench/digital micrometer or comparator under defined contact force, comparing against the nominal blade value. Thickness variation and flatness are recorded at 20 °C. Micrometer resolution and contact force are Type-B contributors.',
    nablReference: 'NABL 122-02',
    referenceStandard: 'Bench micrometer / grade-1 slip gauges',
  },
  {
    id: 'mech-radius-gauge',
    label: 'Radius Gauge',
    discipline: 'Mechanical',
    subDiscipline: 'Dimension — Gauges',
    unit: 'mm',
    points: pts('mm', [1, 3, 5, 10, 15, 25]),
    typeB: tb('mm', 0.005, 0.05, [hysteresisExtra('mm', 0.01)]),
    units: MM_ALT.concat('mm'),
    procedureText:
      'Each radius-gauge leaf (concave and convex) is checked on a profile projector or measuring microscope against the nominal radius template, evaluating the form deviation of the curved edge. Profile error is recorded at 20 °C. Optical reading resolution and edge definition are Type-B contributors.',
    nablReference: 'NABL 122-02',
    referenceStandard: 'Profile projector with calibrated radius reticle',
  },
  {
    id: 'mech-pitch-gauge',
    label: 'Pitch (Screw) Gauge',
    discipline: 'Mechanical',
    subDiscipline: 'Dimension — Gauges',
    unit: 'mm',
    points: pts('mm', [0.5, 0.8, 1, 1.5, 2, 3]),
    typeB: tb('mm', 0.002, 0.01, [hysteresisExtra('mm', 0.005)]),
    units: MM_ALT.concat('mm'),
    procedureText:
      'Each pitch-gauge leaf is checked on a profile projector or measuring microscope by measuring the distance over a number of thread crests and the flank angle, comparing against the nominal pitch and 60°/55° form. Cumulative pitch error is evaluated at 20 °C. Optical resolution is a Type-B contributor.',
    nablReference: 'NABL 122-02',
    referenceStandard: 'Profile projector / measuring microscope',
  },
  {
    id: 'mech-taper-gauge',
    label: 'Taper Gauge',
    discipline: 'Mechanical',
    subDiscipline: 'Dimension — Gauges',
    unit: 'mm',
    points: pts('mm', [5, 10, 20, 30, 50]),
    typeB: tb('mm', 0.0008, 0.001, [hysteresisExtra('mm', 0.001)]),
    units: MM_ALT.concat('mm'),
    procedureText:
      'The taper (plug/ring) gauge is calibrated by measuring diameters at two known axial positions using rollers/balls of known diameter on a length comparator or measuring machine, from which the included taper angle and diameters are computed. Form (straightness of the taper) is assessed. Ball-fit and resolution are Type-B contributors.',
    nablReference: 'NABL 122-02',
    referenceStandard: 'Calibrated precision balls/rollers, length comparator',
  },

  // ── Dimension — Angle ───────────────────────────────────────────────
  {
    id: 'mech-universal-bevel-protractor',
    label: 'Universal Bevel Protractor',
    discipline: 'Mechanical',
    subDiscipline: 'Dimension — Angle',
    unit: '°',
    points: pts('°', [0, 30, 45, 60, 90, 120, 180]),
    typeB: tb('°', 0.0017, 0.0833, [hysteresisExtra('°', 0.005)]),
    units: ANGLE_ALT.concat('°'),
    ranges: [
      range('Angle', '°', [0, 30, 45, 60, 90, 120, 180], tb('°', 0.0017, 0.0833, [hysteresisExtra('°', 0.005)]), { altUnits: ANGLE_ALT, rangeText: '0 – 360 °' }),
    ],
    procedureText:
      'The universal bevel protractor is calibrated against a calibrated angle-gauge-block stack or a precision polygon with an autocollimator at selected angles over the range, including verification of the vernier/acute-angle attachment. Blade straightness and zero setting are checked. Reading resolution (5′) and repeatability are Type-B contributors.',
    nablReference: 'IS 5359',
    referenceStandard: 'Angle gauge blocks / precision polygon & autocollimator',
  },
  {
    id: 'mech-sine-bar',
    label: 'Sine Bar',
    discipline: 'Mechanical',
    subDiscipline: 'Dimension — Angle',
    unit: 'mm',
    points: pts('mm', [100, 200, 250, 300]),
    typeB: tb('mm', 0.0008, 0.001, [hysteresisExtra('mm', 0.0005)]),
    units: MM_ALT.concat('mm'),
    procedureText:
      'The sine bar is calibrated for roller centre distance, roller diameter equality, roller parallelism and flatness of the working surface on a length comparator / surface plate using gauge blocks and an indicator. The derived angular accuracy is computed from the centre-distance error. Indicator resolution and surface-plate flatness are Type-B contributors.',
    nablReference: 'IS 5234',
    referenceStandard: 'Grade-1 slip gauges, grade-0 surface plate, indicator',
  },
  {
    id: 'mech-angle-gauge-blocks',
    label: 'Angle Gauge Blocks',
    discipline: 'Mechanical',
    subDiscipline: 'Dimension — Angle',
    unit: '°',
    points: pts('°', [1, 3, 9, 27, 41, 90]),
    typeB: tb('°', 0.0003, 0.0028, [hysteresisExtra('°', 0.0006)]),
    units: ANGLE_ALT.concat('°'),
    procedureText:
      'Angle gauge blocks are calibrated by comparison against a calibrated precision polygon using an autocollimator on a rotary table, or by wringing combinations against reference angle blocks, evaluating the angle deviation of each block. Flatness of the lapped faces is verified. Autocollimator resolution and wringing effects are Type-B contributors.',
    nablReference: 'NABL 122-02',
    referenceStandard: 'Precision polygon & autocollimator / reference angle blocks',
  },
  {
    id: 'mech-try-engineer-square',
    label: 'Try / Engineer Square',
    discipline: 'Mechanical',
    subDiscipline: 'Dimension — Angle',
    unit: 'mm/m',
    points: pts('mm/m', [0, 0.005, 0.01, 0.02]),
    typeB: tb('mm/m', 0.002, 0.001, [hysteresisExtra('mm/m', 0.002)]),
    units: ['mm/m', '°', 'µm'],
    procedureText:
      'The squareness of the engineer\'s square is calibrated against a calibrated reference square (or cylindrical square) on a surface plate using an indicator/slip-gauge method, measuring the perpendicularity deviation of the blade to the stock over its length. Straightness of the working edges is also checked. Indicator resolution and surface-plate flatness are Type-B contributors.',
    nablReference: 'IS 2103',
    referenceStandard: 'Reference / cylindrical square, grade-0 surface plate',
  },
  {
    id: 'mech-spirit-precision-level',
    label: 'Spirit Level / Precision Level',
    discipline: 'Mechanical',
    subDiscipline: 'Dimension — Angle',
    unit: 'mm/m',
    points: pts('mm/m', [-0.1, -0.05, 0, 0.05, 0.1]),
    typeB: tb('mm/m', 0.002, 0.01, [hysteresisExtra('mm/m', 0.005)]),
    units: ['mm/m', '°', 'arcsec'],
    procedureText:
      'The precision spirit level is calibrated on a calibrated tilting-table / level-calibrator (sine-bar arrangement with gauge blocks) by imparting known inclinations and reading the bubble displacement in graduations, in both directions to assess hysteresis and zero error. The sensitivity per graduation is verified. Resolution and bubble-reading are Type-B contributors.',
    nablReference: 'IS 5429',
    referenceStandard: 'Level calibrator / tilting table with grade-1 slip gauges',
  },

  // ── Dimension — Form & Surface ──────────────────────────────────────
  {
    id: 'mech-surface-plate-flatness',
    label: 'Surface Plate (Flatness)',
    discipline: 'Mechanical',
    subDiscipline: 'Dimension — Form & Surface',
    unit: 'µm',
    points: pts('µm', [0, 2, 5, 10, 20]),
    typeB: tb('µm', 0.3, 0.1, [hysteresisExtra('µm', 0.2)]),
    units: ['µm', 'mm'],
    procedureText:
      'The surface plate is calibrated for overall flatness using the Union Jack diagonal pattern with a precision electronic/spirit level or autocollimator, taking step measurements along the grid lines and reducing the data by the Moody method to the reference plane. Local and overall flatness deviations are reported per IS 2285. Level/autocollimator resolution and temperature are Type-B contributors.',
    nablReference: 'IS 2285',
    referenceStandard: 'Precision electronic level / autocollimator',
  },
  {
    id: 'mech-straight-edge',
    label: 'Straight Edge',
    discipline: 'Mechanical',
    subDiscipline: 'Dimension — Form & Surface',
    unit: 'µm',
    points: pts('µm', [0, 1, 2, 5, 10]),
    typeB: tb('µm', 0.3, 0.1, [hysteresisExtra('µm', 0.2)]),
    units: ['µm', 'mm'],
    procedureText:
      'The straightness of the working edge is calibrated on a grade-0 surface plate by the reversal / indicator method, or with an autocollimator along the edge, recording deviations from a best-fit straight line over the length. Both edges/faces are assessed per IS 2220. Indicator/autocollimator resolution is a Type-B contributor.',
    nablReference: 'IS 2220',
    referenceStandard: 'Grade-0 surface plate, electronic indicator / autocollimator',
  },
  {
    id: 'mech-v-block',
    label: 'V-Block',
    discipline: 'Mechanical',
    subDiscipline: 'Dimension — Form & Surface',
    unit: 'µm',
    points: pts('µm', [0, 2, 5, 10]),
    typeB: tb('µm', 0.3, 0.1, [hysteresisExtra('µm', 0.2)]),
    units: ['µm', 'mm'],
    procedureText:
      'The V-block is calibrated for the included V-angle, symmetry of the vee to the base/sides, parallelism and flatness of the working faces using a calibrated test cylinder, gauge blocks and an indicator on a surface plate. Squareness of the vee to the base is verified per IS 2949. Indicator resolution and cylinder fit are Type-B contributors.',
    nablReference: 'IS 2949',
    referenceStandard: 'Calibrated test cylinder, grade-1 slip gauges, indicator',
  },
  {
    id: 'mech-profile-projector',
    label: 'Profile Projector',
    discipline: 'Mechanical',
    subDiscipline: 'Dimension — Form & Surface',
    unit: 'mm',
    points: pts('mm', [0, 10, 25, 50, 100]),
    typeB: tb('mm', 0.001, 0.001, [hysteresisExtra('mm', 0.002)]),
    units: MM_ALT.concat('mm'),
    ranges: [
      range('Linear (X/Y stage)', 'mm', [0, 10, 25, 50, 100], tb('mm', 0.001, 0.001, [hysteresisExtra('mm', 0.002)]), { altUnits: MM_ALT, rangeText: '0 – 100 mm' }),
      range('Magnification', 'mm', [10, 20, 50, 100], tb('mm', 0.002, 0.001), { rangeText: '10× – 100×' }),
      range('Angle (protractor screen)', '°', [0, 45, 90, 180], tb('°', 0.003, 0.0167), { altUnits: ANGLE_ALT }),
    ],
    procedureText:
      'The profile projector is calibrated for X/Y stage linear accuracy against a calibrated stage micrometer/glass scale, screen magnification using a reference scale, and angular (protractor) accuracy against angle blocks/polygon at selected points. Edge focus and parallax are evaluated. Stage scale and reading resolution are Type-B contributors.',
    nablReference: 'NABL 122-02',
    referenceStandard: 'Reference glass stage micrometer / line scale',
  },
  {
    id: 'mech-measuring-microscope',
    label: 'Measuring Microscope',
    discipline: 'Mechanical',
    subDiscipline: 'Dimension — Form & Surface',
    unit: 'mm',
    points: pts('mm', [0, 5, 10, 25, 50]),
    typeB: tb('mm', 0.0008, 0.001, [hysteresisExtra('mm', 0.001)]),
    units: MM_ALT.concat('mm'),
    ranges: [
      range('Linear (X/Y stage)', 'mm', [0, 5, 10, 25, 50], tb('mm', 0.0008, 0.001, [hysteresisExtra('mm', 0.001)]), { altUnits: MM_ALT, rangeText: '0 – 50 mm' }),
      range('Angle (goniometer eyepiece)', '°', [0, 45, 90, 180], tb('°', 0.0028, 0.0167), { altUnits: ANGLE_ALT }),
    ],
    procedureText:
      'The measuring microscope is calibrated for X/Y stage micrometer accuracy against a calibrated reference glass scale / stage micrometer and for goniometer-eyepiece angular accuracy against a precision polygon or angle blocks at selected points. Crosshair setting repeatability is evaluated. Stage scale and reading resolution are Type-B contributors.',
    nablReference: 'NABL 122-02',
    referenceStandard: 'Reference glass scale / stage micrometer, polygon',
  },
  {
    id: 'mech-coating-thickness-gauge',
    label: 'Coating / Paint Thickness Gauge',
    discipline: 'Mechanical',
    subDiscipline: 'Dimension — Form & Surface',
    unit: 'µm',
    points: pts('µm', [0, 25, 50, 100, 250, 500, 1000]),
    typeB: tb('µm', 0.5, 0.1, [hysteresisExtra('µm', 1)]),
    units: ['µm', 'mm', 'mils'],
    procedureText:
      'The coating thickness gauge (magnetic / eddy-current) is calibrated using certified coating-thickness reference foils placed on the appropriate ferrous or non-ferrous substrate at points across the range, comparing the displayed value with the certified foil thickness. Substrate, curvature and zero effects are evaluated per ISO 2808. Foil uncertainty and resolution are Type-B contributors.',
    nablReference: 'ISO 2808',
    referenceStandard: 'Certified precision foils with ferrous/non-ferrous base plates',
  },
  {
    id: 'mech-ultrasonic-thickness-gauge',
    label: 'Ultrasonic Thickness Gauge',
    discipline: 'Mechanical',
    subDiscipline: 'Dimension — Form & Surface',
    unit: 'mm',
    points: pts('mm', [1, 2, 5, 10, 25, 50]),
    typeB: tb('mm', 0.005, 0.01, [hysteresisExtra('mm', 0.01)]),
    units: ['mm', 'inch'],
    procedureText:
      'The ultrasonic thickness gauge is calibrated using a certified multi-step calibration block of the matched material (sound velocity set accordingly), comparing the displayed thickness with the certified step thicknesses at points across the range after couplant application. Velocity and zero/probe-delay corrections are verified. Block uncertainty and resolution are Type-B contributors.',
    nablReference: 'ASTM E797',
    referenceStandard: 'Certified multi-step ultrasonic calibration block',
  },
  {
    id: 'mech-surface-roughness-tester',
    label: 'Surface Roughness Tester (Ra)',
    discipline: 'Mechanical',
    subDiscipline: 'Dimension — Form & Surface',
    unit: 'µm',
    points: pts('µm', [0.1, 0.4, 0.8, 1.6, 3.2, 6.3]),
    typeB: tb('µm', 0.01, 0.001, [hysteresisExtra('µm', 0.01)]),
    units: ['µm', 'µinch'],
    ranges: [
      range('Roughness Ra', 'µm', [0.1, 0.4, 0.8, 1.6, 3.2, 6.3], tb('µm', 0.01, 0.001, [hysteresisExtra('µm', 0.01)]), { altUnits: ['µinch'], rangeText: '0.1 – 6.3 µm Ra' }),
    ],
    procedureText:
      'The stylus surface-roughness tester is calibrated using certified roughness reference specimens (type C/D groove and random profiles) at several Ra/Rz values, comparing the measured parameter with the certified value under the standard cut-off and traverse length per ISO 4288 / ISO 5436. Stylus condition and traverse calibration are verified. Specimen uncertainty and resolution are Type-B contributors.',
    nablReference: 'ISO 5436-1',
    referenceStandard: 'Certified roughness reference specimens (Ra/Rz)',
  },
  {
    id: 'mech-cmm-verification',
    label: 'CMM (Verification)',
    discipline: 'Mechanical',
    subDiscipline: 'Dimension — Form & Surface',
    unit: 'mm',
    points: pts('mm', [0, 50, 100, 250, 500, 750]),
    typeB: tb('mm', 0.0005, 0.001, [hysteresisExtra('mm', 0.001)]),
    units: MM_ALT.concat('mm'),
    ranges: [
      range('Length measurement error E0', 'mm', [0, 50, 100, 250, 500, 750], tb('mm', 0.0005, 0.001, [hysteresisExtra('mm', 0.001)]), { altUnits: MM_ALT, rangeText: '0 – 1000 mm' }),
      range('Probing error P', 'mm', [0, 0.001, 0.002, 0.003], tb('mm', 0.0005, 0.001)),
    ],
    procedureText:
      'The CMM is verified for length-measurement error (E0/E150) using calibrated gauge blocks or a step gauge / ball bar positioned in several spatial directions, and for probing error (P) by probing a calibrated reference sphere, per ISO 10360-2/5. Measured errors are compared with the manufacturer\'s MPE after thermal stabilisation at 20 °C. Reference-artefact uncertainty and resolution are Type-B contributors.',
    nablReference: 'ISO 10360-2',
    referenceStandard: 'Calibrated step gauge / gauge blocks / reference sphere',
  },
];
